### ISSUE TITLE
The result varies a lof when I use different cluster

### ISSUE THREAD

**Issue by dicklim** [bioturing/py-monocle#15]
Hi, thanks a lot for such a great project. Here are several problems when I was using the script.
1. The input seems to be the umap generated from the expression matrix. I use the umap result from the scanpy. However, I am not sure if it's true. Should I use the expression matrix to learn graph?
2. The reslut seems to change a lot when I use different cell cluster. For example, when I use leiden at resolution 0.5 and 1.0, the result was quiter different. Here is my record. 
```
import py_monocle

projected_points, mst, centroids = py_monocle.learn_graph(
  matrix=alldata.obsm['X_umap'], clusters=alldata.obs["leiden_res1_0"].to_numpy(dtype=int),
)

pseudotime = py_monocle.order_cells(
  alldata.obsm['X_umap'], centroids,
  mst=mst,
  projected_points=projected_points,
  root_cells=0,
)

plt.title("Principal graph")
plt.scatter(alldata.obsm['X_umap'][:, 0], alldata.obsm['X_umap'][:, 1], c=alldata.obs["leiden_res0_5"].to_numpy(dtype=int), s=1, cmap="nipy_spectral")

edges = np.array(mst.nonzero()).T
for edge in edges:
    plt.plot(centroids[edge, 0], centroids[edge, 1], c="black", linewidth=1)
plt.show()

```

**Here are the result,is this reasonable?**
Leiden res 0.5

![图片](https://github.com/bioturing/py-monocle/assets/55022062/3d480227-2e12-4297-9f6e-40bf11a7adbd)
![图片](https://github.com/bioturing/py-monocle/assets/55022062/f7696487-4f29-4ad2-9b7f-fe522ed7b460)

Leiden res 1.0

![图片](https://github.com/bioturing/py-monocle/assets/55022062/94a42e96-4bf2-4f85-833c-9975904854f4)
![图片](https://github.com/bioturing/py-monocle/assets/55022062/b13191a2-1043-49e1-b1b0-ddb5567fa661)

**Comment by nhatnm52** [comment]
1. Using UMAP result is true.
2. The number of clusters in your metadata determines the number of centroids used to find the principal graph, so it may differ when you change the metadata. You can try visualizing with pseudotime to identify some similarities between the results.
