### ISSUE TITLE
Perform differential expression analysis

### ISSUE THREAD

**Issue by dgh4986** [bioturing/py-monocle#16]
Hi, thanks a lot for such a great project. 
I wanted to use this script for differential expression analysis, but couldn't find this module. Can I use py-monocle to perform differential expression analysis like monocle2 or monocle3?

**Comment by nhatnm52** [comment]
You can try the `differential_expression_genes feature`, which is the Python implementation of the `graph_test` feature in Monocle3. I've also included an example to demonstrate how this feature works in in https://github.com/bioturing/py-monocle/pull/19.
